#             SPLINES
# 6 linear spline, one knot
comb <- cbind(seat,fv$floor.vol,ev$electronic.vol)
#head(comb)
comb <- cbind(comb,rep(1:12),trunc(comb$X/12)+1980)
colnames(comb) <- c("X","V1","floor.vol","electronic.vol","month","year")
comb[109,]

par(mfrow=c(1,1))

###############################
par(mfrow=c(2,2))
f.lin <- lm(comb$V1~bs(comb$floor.vol,knots=c(comb[c(109),3]), degree=1))
e.lin <- lm(comb$V1~bs(comb$electronic.vol,knots=c(comb[c(109),4]), degree=1))
c.lin <- lm(comb$V1~bs(comb$vol.sum,knots=c(comb[c(109),7]), degree=1))
plot(comb$V1,ylab='seat price ($)',main='# 6  linear, knot at Jan 1999') 
lines(comb$X,predict(f.lin),col='blue')
lines(comb$X,predict(e.lin),col='red')
lines(comb$X,predict(c.lin),col='dark green')
fr2 <- round(summary(f.lin)$r.squared,digits=6)
er2 <- round(summary(e.lin)$r.squared,digits=6)
cr2 <- round(summary(c.lin)$r.squared,digits=6)
legend("topright", legend=c("floor","electronic","total vol"),
         col=c('blue','red','dark green'),pch=1)
t1=paste("floor R2 = ",fr2,"\nelectronic R2 = ",er2,"\ntotal volume = ",cr2)
text(130,890000,labels=t1)
f.lin <- lm(comb$V1~bs(comb$floor.vol,knots=c(comb[c(61,121,181,241),3]), degree=1))
e.lin <- lm(comb$V1~bs(comb$electronic.vol,knots=c(comb[c(61,121,181,241),4]), degree=1))
c.lin <- lm(comb$V1~bs(comb$vol.sum,knots=c(comb[c(61,121,181,241),7]), degree=1))
plot(comb$V1,ylab='seat price ($)',main='# 6+  linear, knots every 5 years')
lines(comb$X,predict(f.lin),col='blue')
lines(comb$X,predict(e.lin),col='red')
lines(comb$X,predict(c.lin),col='dark green')
fr2 <- round(summary(f.lin)$r.squared,digits=6)
er2 <- round(summary(e.lin)$r.squared,digits=6)
cr2 <- round(summary(c.lin)$r.squared,digits=6)
legend("topright", legend=c("floor","electronic","total vol"),
         col=c('blue','red','dark green'),pch=1)
t1=paste("floor R2 = ",fr2,"\nelectronic R2 = ",er2,"\ntotal volume = ",cr2)
text(130,890000,labels=t1)
f.lin <- lm(comb$V1~bs(comb$floor.vol,knots=c(comb[c(109),3]), degree=3))
e.lin <- lm(comb$V1~bs(comb$electronic.vol,knots=c(comb[c(109),4]), degree=3))
c.lin <- lm(comb$V1~bs(comb$vol.sum,knots=c(comb[c(109),7]), degree=3))
plot(comb$V1,ylab='seat price ($)',main='# 7  cubic, knot at Jan 1999') 
lines(comb$X,predict(f.lin),col='blue')
lines(comb$X,predict(e.lin),col='red')
lines(comb$X,predict(c.lin),col='dark green')
fr2 <- round(summary(f.lin)$r.squared,digits=6)
er2 <- round(summary(e.lin)$r.squared,digits=6)
cr2 <- round(summary(c.lin)$r.squared,digits=6)
legend("topright", legend=c("floor","electronic","total vol"),
         col=c('blue','red','dark green'),pch=1)
t1=paste("floor R2 = ",fr2,"\nelectronic R2 = ",er2,"\ntotal volume = ",cr2)
text(130,890000,labels=t1)
f.lin <- lm(comb$V1~bs(comb$floor.vol,knots=c(comb[c(61,121,181,241),3]), degree=3))
e.lin <- lm(comb$V1~bs(comb$electronic.vol,knots=c(comb[c(61,121,181,241),4]), degree=3))
c.lin <- lm(comb$V1~bs(comb$vol.sum,knots=c(comb[c(61,121,181,241),7]), degree=3))
plot(comb$V1,ylab='seat price ($)',main='# 8  cubic, knots every 5 years')
lines(comb$X,predict(f.lin),col='blue')
lines(comb$X,predict(e.lin),col='red')
lines(comb$X,predict(c.lin),col='dark green')
fr2 <- round(summary(f.lin)$r.squared,digits=6)
er2 <- round(summary(e.lin)$r.squared,digits=6)
cr2 <- round(summary(c.lin)$r.squared,digits=6)
legend("topright", legend=c("floor","electronic","total vol"),
         col=c('blue','red','dark green'),pch=1)
t1=paste("floor R2 = ",fr2,"\nelectronic R2 = ",er2,"\ntotal volume = ",cr2)
text(130,890000,labels=t1)
###############################
